"""Verbatim seed data extracted from the Audree mockup's JS constants
(M_INTENT, M_INPUT, M_IAM, M_CAP, M_AGENTREG, M_RULE, M_WF, M_OUT, M_TOOL,
M_KSR, M_ROLE, M_OUTTPL, M_PROMPT, TEMPLATES, P_PRODUCTS/P_INV/P_LINES/P_QC).
"""

MASTERS = {
    "intent": {
        "title": "Intent Master",
        "cols": ["Intent Code", "Intent Name", "Category", "Allowed Roles", "Required Inputs",
                 "Optional Inputs", "Required Capabilities", "Output Template", "Default Workflow",
                 "Status", "Version"],
        "rows": [
            ["INT-PPIC-001", "Order Commitment Check", "PPIC", "BD, PPIC User, PPIC Head, Plant Head, MD",
             "product, quantity, required_date, plant", "customer, market, priority",
             "CAP-PROD-001, CAP-MAT-001, CAP-CAP-001, CAP-QC-001, CAP-PROC-001, CAP-FIN-001, CAP-RISK-001, CAP-REC-001, CAP-WF-001",
             "Commitment Decision Template", "Order Commitment Approval", "Active", "v1.0"],
            ["INT-PPIC-002", "Production Feasibility Check", "PPIC", "PPIC User, PPIC Head, Plant Head",
             "product/order, quantity, line, window", "priority",
             "CAP-CAP-001, CAP-MAT-001, CAP-QC-001, CAP-RISK-001, CAP-REC-001",
             "Feasibility Decision Template", "Production Approval", "Active", "v1.0"],
            ["INT-MM-001", "Material Availability Check", "Materials", "PPIC User, PPIC Planner, Warehouse User",
             "batch/product, materials", "plant", "CAP-MAT-001", "Material Status Template",
             "Procurement Action", "Active", "v1.0"],
            ["INT-INV-002", "Inventory Status Query", "Warehouse", "BD, PPIC User, Warehouse User",
             "material or product", "plant", "CAP-MAT-001", "Inventory Status Template",
             "Information Only", "Active", "v1.0"],
            ["INT-PPIC-003", "Production Plan Query", "PPIC", "BD, PPIC User, PPIC Head, Plant Head",
             "—", "line, period", "CAP-CAP-001", "Plan Summary Template", "Information Only", "Active", "v1.0"],
            ["INT-PROC-001", "Procurement Recommendation", "Procurement", "Procurement User, Procurement Head",
             "material", "quantity, vendor",
             "CAP-PROC-001, CAP-FIN-001, CAP-RISK-001, CAP-REC-001",
             "Procurement Recommendation Template", "PO Approval", "Active", "v1.0"],
            ["INT-INV-001", "Inventory Replenishment", "Warehouse", "Warehouse User, Warehouse Head",
             "material/category, site", "period", "CAP-MAT-001, CAP-REC-001",
             "Replenishment Template", "Replenishment", "Active", "v1.0"],
            ["INT-QA-001", "Batch Release Decision", "QA", "QA User, QA Head (QP)", "batch", "product",
             "CAP-QC-001, CAP-RISK-001, CAP-REC-001", "Release Decision Template", "QA Approval",
             "Active", "v1.0"],
            ["INT-EXEC-001", "Executive KPI Query", "Executive", "MD, CEO, Business Head", "scope, period",
             "plant", "CAP-CUST-001, CAP-FIN-001, CAP-RISK-001, CAP-REC-001",
             "Executive Summary Template", "Information Only", "Active", "v1.0"],
        ],
    },
    "input": {
        "title": "Input Master (Intent Parameter Master)",
        "cols": ["Seq", "Field Name", "Display Label", "Data Type", "Mandatory", "Validation Rule", "UI Control"],
        "rows": [
            ["1", "product", "Product", "string", "Yes",
             "Must resolve to Product Master (alias / SAP material code mapping)", "autocomplete"],
            ["2", "quantity", "Quantity", "number", "Yes", "> 0; UOM required or inferred from product", "textbox"],
            ["3", "required_date", "Required Delivery Date", "date", "Yes", "Valid future date (business calendar)",
             "datepicker"],
            ["4", "plant", "Plant", "enum", "Yes", "Active plant; user authorized for plant", "dropdown"],
            ["5", "customer", "Customer", "string", "No", "Must resolve to active CRM customer", "autocomplete"],
            ["6", "market", "Market", "enum", "No", "Must map to Market Master", "dropdown"],
            ["7", "priority", "Priority", "enum", "No", "High / Normal / Low · default Normal", "dropdown"],
        ],
    },
    "iam": {
        "title": "Intent–Agent Mapping Master",
        "cols": ["Seq", "Capability", "Primary Agent", "Fallback Agent", "Execution Mode", "Run Type",
                 "Dependency", "Mandatory", "Approval Required"],
        "rows": [
            ["1", "Product Identification (CAP-PROD-001)", "Product Master Agent", "SAP SD Agent", "Read-only",
             "Sequential", "None", "Yes", "No"],
            ["2", "Material Check (CAP-MAT-001)", "Inventory Agent", "SAP MM Agent", "Read-only", "Parallel",
             "Product Identification", "Yes", "No"],
            ["2", "Capacity Check (CAP-CAP-001)", "Capacity Agent", "SAP PP Agent", "Read-only", "Parallel",
             "Product Identification", "Yes", "No"],
            ["2", "QC Check (CAP-QC-001)", "QC Planning Agent", "LIMS Agent", "Read-only", "Parallel",
             "Product Identification", "Yes", "No"],
            ["3", "Procurement Check (CAP-PROC-001)", "Procurement Agent", "SAP MM Agent", "Recommend", "Parallel",
             "Material Check", "No", "No"],
            ["3", "Finance Check (CAP-FIN-001)", "Finance Agent", "Finance System Agent", "Read-only", "Parallel",
             "Product Identification", "No", "No"],
            ["4", "Risk Analysis (CAP-RISK-001)", "Risk Agent", "PPIC Agent", "Recommend", "Sequential",
             "Material, Capacity, QC", "Yes", "No"],
            ["5", "Final Recommendation (CAP-REC-001)", "Recommendation Agent", "PPIC Agent", "Recommend",
             "Sequential", "Risk Analysis", "Yes", "No"],
            ["6", "Workflow Execution (CAP-WF-001)", "Workflow Agent", "Notification Agent",
             "Execute after approval", "Sequential", "Final Recommendation", "No", "Yes"],
        ],
    },
    "cap": {
        "title": "Capability Registry Master",
        "cols": ["Capability Code", "Capability Name", "Type", "Description", "Possible Agents", "Exec. Mode",
                 "Status"],
        "rows": [
            ["CAP-PROD-001", "Product Identification", "Business",
             "Identifies product, dosage, pack, market and product master mapping",
             "Product Master Agent, SAP SD Agent, PPIC Agent", "Read-only", "Active"],
            ["CAP-MAT-001", "Material Check", "Business",
             "API, excipient & packing material availability, open POs, shortages, lead time",
             "Inventory Agent, SAP MM Agent, WMS Agent", "Read-only", "Active"],
            ["CAP-CAP-001", "Capacity Check", "Business", "Plant, line, machine and production capacity availability",
             "Capacity Agent, SAP PP Agent, PPIC Agent", "Read-only", "Active"],
            ["CAP-QC-001", "QC Check", "Business",
             "QC workload, release feasibility, open quality constraints, testing capacity",
             "QC Planning Agent, LIMS Agent, QMS Agent", "Read-only", "Active"],
            ["CAP-PROC-001", "Procurement Check", "Business",
             "Procurement gaps, supplier lead times, open POs, purchase recommendations",
             "Procurement Agent, SAP MM Agent", "Recommend", "Active"],
            ["CAP-FIN-001", "Finance Check", "Business",
             "Cost, margin, credit limit, budget and working-capital impact",
             "Finance Agent, SAP CO/FI Agent", "Read-only", "Active"],
            ["CAP-CUST-001", "Customer Commitment", "Business", "Customer order and delivery feasibility",
             "CRM Agent, SAP SD Agent, PPIC Agent", "Read-only", "Active"],
            ["CAP-RISK-001", "Risk Analysis", "Decision",
             "Delay, shortage, QC, capacity, cost, compliance and customer commitment risks",
             "Risk Agent, PPIC Agent, QA Agent, Finance Agent", "Recommend", "Active"],
            ["CAP-REC-001", "Final Recommendation", "Decision",
             "Consolidates outputs → Can Commit / Cannot Commit / Commit with Conditions / Revise Date / Partial / Escalate / Hold",
             "Recommendation Agent, PPIC Agent, Executive Decision Agent", "Recommend", "Active"],
            ["CAP-WF-001", "Workflow / Action Execution", "Execution",
             "Converts approved decisions into tasks, approvals, notifications, reservations, escalations, system actions",
             "Workflow Agent, Action Agent, Notification Agent, Approval Agent, SAP Action Agent",
             "Execute after approval", "Active"],
        ],
    },
    "agent": {
        "title": "Agent Register Master",
        "cols": ["Agent ID", "Agent Name", "Category", "Supported Capabilities", "Systems Accessed", "Exec. Mode",
                 "Timeout", "Retry Policy", "Status"],
        "rows": [
            ["AGT-PPIC-001", "PPIC Agent", "Functional", "PROD, MAT, CAP, QC, PROC, CUST, RISK, REC",
             "SAP PP/MM/SD, WMS, LIMS/QMS, CRM, Finance", "Recommend; Execute after approval", "60s",
             "Retry once → partial result, mark missing source", "Active"],
            ["AGT-QA-001", "QA Agent", "Functional", "QC, RISK, REC", "LIMS/QMS, DMS", "Recommend", "60s",
             "Retry once → partial", "Active"],
            ["AGT-DOM-001", "Inventory Agent", "Domain", "MAT", "SAP MM, WMS", "Read-only", "30s",
             "Retry once → fallback SAP MM Agent", "Active"],
            ["AGT-DOM-002", "Capacity Agent", "Domain", "CAP", "SAP PP, MES", "Read-only", "30s",
             "Retry once → fallback SAP PP Agent", "Active"],
            ["AGT-DOM-003", "QC Planning Agent", "Domain", "QC", "LIMS/QMS", "Read-only", "30s",
             "Retry once → fallback LIMS Agent", "Active"],
            ["AGT-DOM-004", "Procurement Agent", "Domain", "PROC", "SAP MM", "Recommend", "30s",
             "Retry once → fallback SAP MM Agent", "Active"],
            ["AGT-DOM-005", "Finance Agent", "Domain", "FIN", "Finance ERP, SAP CO/FI", "Read-only", "30s",
             "Retry once → fallback Finance System Agent", "Active"],
            ["AGT-DOM-006", "Risk Agent", "Domain", "RISK", "—", "Recommend", "30s",
             "Retry once → fallback PPIC Agent", "Active"],
            ["AGT-DOM-007", "Recommendation Agent", "Domain", "REC", "—", "Recommend", "30s",
             "Retry once → fallback PPIC Agent", "Active"],
            ["AGT-DOM-008", "Product Master Agent", "Domain", "PROD", "SAP SD", "Read-only", "20s",
             "Retry once → fallback SAP SD Agent", "Active"],
            ["AGT-EXEC-001", "Executive Agent", "Executive", "CUST, FIN, RISK, REC", "All systems (read)",
             "Read-only", "30s", "Retry once → partial", "Active"],
            ["AGT-SYS-001", "SAP MM Agent", "System", "MAT, PROC", "SAP MM", "Read-only", "30s", "Retry twice",
             "Active"],
            ["AGT-SYS-002", "SAP PP Agent", "System", "CAP", "SAP PP", "Read-only", "30s", "Retry twice", "Active"],
            ["AGT-SYS-003", "SAP SD Agent", "System", "PROD, CUST", "SAP SD", "Read-only", "30s", "Retry twice",
             "Active"],
            ["AGT-SYS-004", "LIMS Agent", "System", "QC", "LIMS/QMS", "Read-only", "30s", "Retry twice", "Active"],
            ["AGT-UTL-001", "Workflow Agent", "Utility", "WF", "Workflow Engine", "Execute after approval", "30s",
             "Retry once → fallback Notification Agent", "Active"],
            ["AGT-UTL-002", "Notification Agent", "Utility", "WF (notify)", "Notification Engine", "Execute", "15s",
             "Retry twice", "Active"],
        ],
    },
    "rule": {
        "title": "Rule Mapping Master",
        "cols": ["Rule ID", "Rule Name", "Type", "Applies To", "Condition", "Action", "Severity", "Blocking",
                 "Status"],
        "rows": [
            ["RM-PPIC-001", "BOM Confidentiality", "Security",
             "INT-PPIC-001 · Material Check · PPIC/Inventory Agent · roles BD, PPIC User",
             "User is not authorized for BOM", "Show only material status, not BOM/recipe", "Critical", "Yes",
             "Active"],
            ["RM-PPIC-002", "QC Mandatory Check", "Validation", "INT-PPIC-001 · QC Check · QC Planning Agent",
             "Product requires QC release", "QC feasibility must be checked before commitment", "High", "Yes",
             "Active"],
            ["RM-PPIC-003", "Capacity Conflict Check", "Business", "INT-PPIC-002 · Capacity Check · Capacity Agent",
             "Existing production order overlaps", "Mark capacity risk", "Medium", "No", "Active"],
            ["RM-PPIC-004", "High Risk Escalation", "Escalation", "Risk Analysis · Risk Agent", "Risk level = High",
             "Escalate to PPIC Head / MD", "High", "No", "Active"],
            ["RM-PPIC-005", "Approval Before Execution", "Approval",
             "INT-PPIC-001 · Workflow Execution · Workflow Agent", "Action mode = Execute",
             "Require approval before PO / reservation / workflow action", "Critical", "Yes", "Active"],
            ["RM-INV-001", "Minimum Stock", "Business", "Inventory / Material Check", "Stock < Safety Stock",
             "Flag replenishment requirement", "Medium", "No", "Active"],
            ["RM-FIN-001", "Credit Approval", "Approval", "Finance / Procurement",
             "PR value above threshold (₹10,00,000)", "Route to approval before creation", "High", "Yes", "Active"],
            ["RM-QA-001", "Deviation Block", "Compliance", "INT-QA-001 · QC Check",
             "Open critical deviation on batch", "Block release; route to QA review", "Critical", "Yes", "Active"],
        ],
    },
    "wf": {
        "title": "Workflow Mapping Master",
        "cols": ["Intent", "Decision Output", "Trigger Condition", "Action Type", "Workflow Name", "Assigned Role",
                 "Approval", "Approval Role", "Integration Action", "Target System"],
        "rows": [
            ["INT-PPIC-001", "Can Commit", "Risk = Low", "Notification", "Commitment Confirmation", "BD User",
             "No", "—", "Notify user", "Notification Engine"],
            ["INT-PPIC-001", "Commit with Conditions", "Risk = Medium", "Approval",
             "Conditional Commitment Approval", "PPIC Head", "Yes", "PPIC Head",
             "Reserve capacity after approval", "SAP PP / Workflow"],
            ["INT-PPIC-001", "Cannot Commit", "Material Shortage", "Task", "Procurement Action", "Procurement Team",
             "No", "—", "Create procurement task", "Workflow Engine / SAP MM"],
            ["INT-PPIC-001", "Commit with Risk", "QC Slot Risk", "Escalation", "QC Risk Review", "QA Head", "Yes",
             "QA Head", "Create QC review task", "QMS / Workflow"],
            ["INT-PPIC-001", "High Risk", "Risk = High", "Escalation", "Management Review", "PPIC Head / MD", "Yes",
             "MD", "Escalate decision", "Workflow Engine"],
            ["INT-PROC-001", "Create Purchase Requisition", "PR > ₹10,00,000", "Approval", "PO Approval",
             "Procurement Head", "Yes", "Procurement Head", "Create PR after approval", "SAP MM"],
            ["INT-QA-001", "Release", "All release conditions met", "Approval", "QA Release Approval",
             "QA Head (QP)", "Yes", "QA Head (QP)", "Update release status; archive batch record", "LIMS/QMS · DMS"],
            ["INT-INV-001", "Reorder Recommended", "Reorder point crossed", "Task", "Replenishment",
             "Warehouse Head", "No", "—", "Post replenishment proposal", "SAP MM"],
        ],
    },
    "out": {
        "title": "Standard Agent Output Format",
        "cols": ["Output Field", "Description"],
        "rows": [
            ["Agent ID", "Which agent responded"],
            ["Capability", "Capability handled by the agent"],
            ["Status", "Success / Partial / Failed"],
            ["Result Summary", "Business-readable result"],
            ["Detailed Findings", "Structured findings"],
            ["Risk Level", "Low / Medium / High"],
            ["Confidence Score", "AI / data confidence score"],
            ["Missing Data", "Data not available or source unavailable"],
            ["Recommended Actions", "Suggested actions"],
            ["Source References", "Systems / data used"],
            ["Execution Time", "Time taken"],
            ["Error Details", "Error details if failed"],
        ],
    },
    "tool": {
        "title": "Tool Registry Master",
        "cols": ["Tool Code", "Tool Name", "Category", "Method", "Auth", "Write Tool", "Approval Req.", "Timeout",
                 "Status"],
        "rows": [
            ["GET_WMS_STOCK", "WMS Inventory Lookup", "WMS", "GET / JDBC", "OAuth2", "No", "No", "10s", "Active"],
            ["SAP_MM_OPEN_POS", "SAP Open Purchase Orders", "SAP", "RFC / OData", "RFC", "No", "No", "15s", "Active"],
            ["SAP_PP_CAPACITY_CHECK", "SAP Capacity Check", "SAP", "RFC", "RFC", "No", "No", "15s", "Active"],
            ["SAP_SD_OPEN_ORDERS", "SAP Open Sales Orders", "SAP", "OData", "OAuth2", "No", "No", "15s", "Active"],
            ["LIMS_BATCH_STATUS", "LIMS Batch Status", "LIMS/QMS", "GET", "API Key", "No", "No", "10s", "Active"],
            ["LIMS_COA_RESULTS", "LIMS CoA Results", "LIMS/QMS", "GET", "API Key", "No", "No", "10s", "Active"],
            ["QMS_DEVIATIONS", "QMS Deviations & CAPA", "LIMS/QMS", "GET", "API Key", "No", "No", "10s", "Active"],
            ["DMS_BATCH_RECORD", "DMS Batch Record", "DMS", "GET", "OAuth2", "No", "No", "10s", "Active"],
            ["FIN_BUDGET_CHECK", "Finance Budget Check", "Finance", "GET", "OAuth2", "No", "No", "10s", "Active"],
            ["CRM_CUSTOMER_ORDERS", "CRM Customer Profile & Orders", "CRM", "GET", "OAuth2", "No", "No", "10s",
             "Active"],
            ["SAP_MM_CREATE_PR", "SAP Create Purchase Requisition", "SAP", "POST / RFC", "RFC", "Yes", "Yes", "20s",
             "Active"],
            ["SAP_PP_RESERVE_CAPACITY", "SAP Reserve Capacity", "SAP", "POST / RFC", "RFC", "Yes", "Yes", "20s",
             "Active"],
            ["LIMS_UPDATE_RELEASE", "LIMS Update Release Status", "LIMS/QMS", "PATCH", "API Key", "Yes", "Yes",
             "15s", "Active"],
            ["NOTIFY_TEAMS", "Send Teams Notification", "Communication", "POST", "OAuth2", "No", "No", "10s",
             "Active"],
            ["NOTIFY_EMAIL", "Send Email", "Communication", "POST", "OAuth2", "No", "No", "10s", "Active"],
        ],
    },
    "ksr": {
        "title": "Knowledge Source Registry",
        "cols": ["Source", "Type", "Integration", "Authoritative For", "Business Owner", "Priority"],
        "rows": [
            ["SAP (PP/MM/SD/CO-FI)", "Structured", "RFC / OData", "Materials, production, orders, capacity, finance",
             "IT / SAP CoE", "1"],
            ["WMS", "Structured", "JDBC / REST", "Stock, reservations, warehouse movements", "Warehouse Head", "1"],
            ["LIMS / QMS", "Structured + Documents", "REST API",
             "QC results, specs, deviations, CAPA, release status", "QA Head", "1"],
            ["CRM", "Structured", "REST API", "Customers, open orders, commitments", "Sales Head", "1"],
            ["Finance ERP", "Structured", "OData / API", "Budget, credit, cost, cash flow", "Finance Head", "1"],
            ["MES", "Events + Structured", "Kafka / MQTT", "Line status, equipment, batch execution",
             "Production Head", "2"],
            ["SharePoint / DMS", "Documents", "Connector + OCR", "SOPs, batch records, CoA, validation documents",
             "Doc Control / QA", "2"],
            ["Email / Teams", "Unstructured", "Listener", "Approvals context, communications", "IT", "3"],
            ["IoT Devices", "Events", "MQTT / Kafka", "Equipment signals, alerts", "Engineering", "3"],
            ["Azure Data Lake", "Structured", "JDBC", "History, analytics, forecasts", "Data Team", "2"],
            ["External APIs", "Structured", "REST", "Vendor lead times, market data", "Procurement", "3"],
        ],
    },
    "role": {
        "title": "Role Permission Master",
        "cols": ["Intent", "Role", "Permission"],
        "rows": [
            ["INT-PPIC-001 Order Commitment Check", "BD", "Request"],
            ["INT-PPIC-001 Order Commitment Check", "PPIC User", "Request"],
            ["INT-PPIC-001 Order Commitment Check", "PPIC Head", "Request · Approve"],
            ["INT-PPIC-001 Order Commitment Check", "Plant Head", "View · Approve"],
            ["INT-PPIC-001 Order Commitment Check", "MD", "View escalations · Final approval (High Risk)"],
            ["INT-PPIC-002 Production Feasibility", "PPIC Head / Plant Head", "Request · Approve"],
            ["INT-MM-001 Material Availability", "PPIC Planner, Warehouse User", "Request"],
            ["INT-PROC-001 Procurement Recommendation", "Procurement User", "Request"],
            ["INT-PROC-001 Procurement Recommendation", "Procurement Head", "Approve"],
            ["INT-INV-001 Inventory Replenishment", "Warehouse User / Head", "Request · Acknowledge"],
            ["INT-QA-001 Batch Release", "QA User", "Request"],
            ["INT-QA-001 Batch Release", "QA Head (Qualified Person)", "Approve (Release / Hold / Reject)"],
            ["INT-EXEC-001 Executive KPI Query", "MD, CEO, Business Head", "Request · View"],
        ],
    },
    "outtpl": {
        "title": "Output Template Master",
        "cols": ["Template", "Intent", "Response Structure (fields)", "Status"],
        "rows": [
            ["Commitment Decision Template", "INT-PPIC-001",
             "Decision (Can/Cannot/Conditions) · earliest completion date · material status · capacity status · QC status · procurement gap · risk level · confidence · recommended actions",
             "Active"],
            ["Feasibility Decision Template", "INT-PPIC-002",
             "Feasibility (Yes/With constraints/No) · constraint list · suggested schedule shift · risk · confidence · actions",
             "Active"],
            ["Material Status Template", "INT-MM-001",
             "Per-material availability · shortage quantity · expected availability date · open POs · actions",
             "Active"],
            ["Procurement Recommendation Template", "INT-PROC-001",
             "Recommended action (PR / expedite / alternate vendor / safety stock) · quantity · vendor · budget check · risk · actions",
             "Active"],
            ["Replenishment Template", "INT-INV-001",
             "Reorder quantity · reorder date · stockout risk % · consumption trend · actions", "Active"],
            ["Release Decision Template", "INT-QA-001",
             "Decision (Release/Hold/Reject) · CoA summary · deviations & CAPA status · stability status · risk · confidence",
             "Active"],
            ["Executive Summary Template", "INT-EXEC-001",
             "Key insight headline · at-risk items · financial impact · root cause · recommended executive actions",
             "Active"],
        ],
    },
    "prompt": {
        "title": "Prompt Template Master",
        "cols": ["Prompt Type", "Purpose", "Example Target", "Variables", "Lifecycle Status"],
        "rows": [
            ["System Prompt", "Defines AI behavior, guardrails, refusal rules", "All agents",
             "{platform_rules}, {security_policy}", "Active v1.2"],
            ["Business Prompt", "Business-specific instructions per intent", "INT-PPIC-001 agents",
             "{intent}, {plant_policies}", "Active v1.1"],
            ["Agent Prompt", "Agent execution instructions per capability", "Inventory Agent · Material Check",
             "{capability}, {required_inputs}, {output_schema}", "Active v1.0"],
            ["Context Prompt", "Formats the Business Context Package for the LLM", "Context Builder",
             "{business_entities}, {enterprise_data}, {knowledge_refs}", "Active v1.0"],
            ["Response Prompt", "Standardizes output to Standard Agent Output Format", "Result Formatter",
             "{output_template}, {confidence_required}", "Active v1.0"],
            ["Validation Prompt", "Checks response quality before aggregation", "Runtime Manager",
             "{agent_output}, {json_schema}", "Active v1.0"],
            ["Safety Prompt", "Prevents unsafe / confidential responses (BOM, recipe, pricing)", "All agents",
             "{masking_rules}, {role}", "Active v1.3"],
            ["Clarification Prompt", "Generates structured questions for missing inputs",
             "Intent Engine · Clarification Builder", "{missing_fields}, {ui_labels}", "Active v1.0"],
        ],
    },
}

MASTER_ORDER = ["intent", "input", "iam", "cap", "agent", "rule", "wf", "out", "tool", "ksr", "role", "outtpl",
                "prompt"]

# ------------------- Business scenarios (BR-001..BR-007) -------------------

TEMPLATES = [
    {"br": "BR-001", "code": "INT-PPIC-001", "ind": "PPIC / Planning", "name": "Order Commitment Check",
     "perf": "≤ 30 seconds", "owner": "PPIC Head",
     "desc": "\"Can we commit 10M capsules by 30 Sept?\" — material, capacity, QC, finance and risk, without exposing BOMs or recipes.",
     "goal": "Determine whether a customer order can be committed based on material availability, production capacity, quality constraints, procurement lead times and existing commitments, while protecting confidential manufacturing information.",
     "caps": ["Product Identification", "Material Check", "Capacity Check", "QC Check", "Procurement Check",
              "Finance Check", "Risk Analysis", "Final Recommendation", "Workflow Execution"],
     "agents": ["Product Master Agent", "Inventory Agent", "Capacity Agent", "QC Planning Agent",
                "Procurement Agent", "Finance Agent", "Risk Agent", "Recommendation Agent"],
     "plan": "1 Product Identification → Product Master Agent (fb SAP SD) · 2∥ Material / Capacity / QC · 3∥ Procurement / Finance · 4 Risk Analysis · 5 Final Recommendation · 6 Workflow Execution (after approval)",
     "outputs": "Material = PARTIAL (1 WMS source marked missing) · Capacity = AVAILABLE · QC = RISK (testing slot) · Finance = OK",
     "systems": ["SAP PP", "SAP MM", "SAP SD", "WMS", "LIMS/QMS", "Finance ERP"],
     "kb": ["Product Master", "Inventory", "Production Plan", "Purchase Orders", "Open Sales Orders",
            "Quality Calendar", "Machine Capacity", "Vendor Lead Times"],
     "tools": ["GET_WMS_STOCK", "SAP_PP_CAPACITY_CHECK", "LIMS_BATCH_STATUS", "SAP_SD_OPEN_ORDERS"],
     "rules": [{"name": "BOM Confidentiality (RM-PPIC-001) — hide BOM/recipe", "gate": False},
               {"name": "QC Mandatory Check (RM-PPIC-002)", "gate": False},
               {"name": "Existing commitments take precedence", "gate": False},
               {"name": "Commit with Conditions (Risk=Medium) requires PPIC Head approval", "gate": True}],
     "notif": ["Microsoft Teams", "Email"], "workflow": "Conditional Commitment Approval (Risk = Medium → PPIC Head)"},
    {"br": "BR-002", "code": "INT-PPIC-002", "ind": "Production", "name": "Production Feasibility Check",
     "perf": "≤ 30 seconds", "owner": "Plant Head",
     "desc": "Can a proposed production order be executed within the requested timeline?",
     "goal": "Assess whether a proposed production order can be executed within the requested timeline across capacity, material, quality and equipment constraints.",
     "caps": ["Capacity Check", "Material Check", "QC Check", "Risk Analysis", "Final Recommendation"],
     "agents": ["Capacity Agent", "Material Agent", "QC Planning Agent", "Equipment Agent", "Risk Agent"],
     "plan": "1∥ Capacity / Material / QC / Equipment · 2 Risk Analysis · 3 Recommendation",
     "outputs": "Capacity = CONFLICT on Line 3 (existing order overlap · RM-PPIC-003) · Material = OK · QC = OK · Equipment = OK",
     "systems": ["SAP PP", "MES", "WMS"], "kb": ["Production Plan", "Machine Capacity", "Inventory", "Quality Calendar"],
     "tools": ["SAP_PP_CAPACITY_CHECK", "MES_LINE_STATUS", "GET_WMS_STOCK"],
     "rules": [{"name": "Capacity Conflict Check (RM-PPIC-003)", "gate": False},
               {"name": "Production plan change requires approval", "gate": True}],
     "notif": ["Microsoft Teams"], "workflow": "Production Approval (Plant Head)"},
    {"br": "BR-003", "code": "INT-MM-001", "ind": "Materials", "name": "Material Availability Check",
     "perf": "≤ 20 seconds", "owner": "PPIC Planner",
     "desc": "Are required materials available to support production? Shortage quantity and expected availability.",
     "goal": "Determine whether required materials are available to support production, using inventory, open POs, vendor deliveries and reservations.",
     "caps": ["Material Check"], "agents": ["Inventory Agent", "Procurement Agent", "Material Agent"],
     "plan": "1∥ Material Check (Inventory / Procurement / Material) · 2 Consolidation",
     "outputs": "Inventory = OK for 5 of 6 materials · Shortage = 120 kg (excipient E-204) · reservations excluded (RM-INV-001)",
     "systems": ["SAP MM", "WMS"], "kb": ["Inventory", "Purchase Orders", "Vendor Lead Times", "Product Master"],
     "tools": ["GET_WMS_STOCK", "SAP_MM_OPEN_POS"],
     "rules": [{"name": "Reserved material excluded from availability", "gate": False}],
     "notif": ["In-App Alert"], "workflow": "Procurement Action → Procurement Team"},
    {"br": "BR-004", "code": "INT-PROC-001", "ind": "Procurement", "name": "Procurement Recommendation",
     "perf": "≤ 30 seconds", "owner": "Procurement Head",
     "desc": "Recommend PR creation, PO expedite, alternate vendor, or safety-stock changes to avoid delays.",
     "goal": "Recommend procurement actions to avoid production delays.",
     "caps": ["Procurement Check", "Finance Check", "Risk Analysis", "Final Recommendation"],
     "agents": ["Procurement Agent", "Inventory Agent", "Vendor Agent", "Finance Agent"],
     "plan": "1∥ Procurement / Inventory / Vendor / Finance · 2 Risk · 3 Recommendation",
     "outputs": "Open POs = 2 (late) · Vendor lead time = 18 days · Budget = OK · stockout in 12 days",
     "systems": ["SAP MM", "Finance ERP"],
     "kb": ["Purchase Orders", "Vendor Lead Times", "Inventory", "Forecast & Consumption"],
     "tools": ["SAP_MM_CREATE_PR", "FIN_BUDGET_CHECK", "SAP_MM_OPEN_POS"],
     "rules": [{"name": "Preferred vendor list applies", "gate": False},
               {"name": "Credit Approval (RM-FIN-001) — PR above ₹10,00,000", "gate": True}],
     "notif": ["Email", "Microsoft Teams"], "workflow": "PO Approval (Procurement Head)"},
    {"br": "BR-005", "code": "INT-INV-001", "ind": "Warehouse", "name": "Inventory Replenishment",
     "perf": "≤ 20 seconds", "owner": "Warehouse Head",
     "desc": "Reorder quantity, reorder date and stockout risk from demand, consumption, lead time and safety stock.",
     "goal": "Recommend inventory replenishment based on demand, consumption trends, lead time, and safety stock.",
     "caps": ["Material Check", "Final Recommendation"], "agents": ["Inventory Agent", "Recommendation Agent"],
     "plan": "1 Inventory Analysis · 2 Recommendation",
     "outputs": "Stock = 12 days cover · Consumption trend = +8% · Safety stock breach in 9 days (RM-INV-001)",
     "systems": ["WMS", "SAP MM"], "kb": ["Inventory", "Forecast & Consumption", "Vendor Lead Times"],
     "tools": ["GET_WMS_STOCK", "SAP_MM_CONSUMPTION"],
     "rules": [{"name": "Minimum Stock rule (RM-INV-001) — Stock ≥ Safety Stock", "gate": False}],
     "notif": ["In-App Alert"], "workflow": "Replenishment (auto-notify Warehouse Head)"},
    {"br": "BR-006", "code": "INT-QA-001", "ind": "Quality / QA", "name": "Batch Release Decision",
     "perf": "≤ 30 seconds", "owner": "QA Head (Qualified Person)",
     "desc": "Assists QA in Release / Hold / Reject using LIMS, QMS, stability, deviations, CAPA, OOS/OOT.",
     "goal": "Assist QA in deciding whether a manufacturing batch is ready for release.",
     "caps": ["QC Check", "Risk Analysis", "Final Recommendation"],
     "agents": ["QA Agent", "Compliance Agent", "Risk Agent"],
     "plan": "1∥ QC Check / Compliance · 2 Risk · 3 Recommendation",
     "outputs": "CoA = ALL IN SPEC · Deviations = CLOSED (RM-QA-001 pass) · CAPA = NONE OPEN · Stability = OK",
     "systems": ["LIMS/QMS", "Documents (DMS)", "SAP PP"],
     "kb": ["Deviations & CAPA", "Stability Data", "Quality Calendar", "SOPs & Policies", "Batch Records & CoA"],
     "tools": ["LIMS_COA_RESULTS", "QMS_DEVIATIONS", "DMS_BATCH_RECORD", "LIMS_UPDATE_RELEASE"],
     "rules": [{"name": "All CoA results within specification", "gate": False},
               {"name": "Deviation Block (RM-QA-001) — open critical deviations block release", "gate": False},
               {"name": "Batch release decision requires QA (QP) approval", "gate": True}],
     "notif": ["Email", "Microsoft Teams"], "workflow": "QA Release Approval (Qualified Person)"},
    {"br": "BR-007", "code": "INT-EXEC-001", "ind": "Executive", "name": "Executive KPI Query",
     "perf": "≤ 15 seconds", "owner": "MD / CEO",
     "desc": "AI-driven executive insights: production risks, at-risk commitments, cash-flow impact, capacity constraints.",
     "goal": "Provide executives with AI-driven insights and recommendations from enterprise data.",
     "caps": ["Customer Commitment", "Finance Check", "Risk Analysis", "Final Recommendation"],
     "agents": ["Executive Agent", "Finance Agent", "Operations Agent", "Risk Agent"],
     "plan": "1∥ Commitments / Finance / Operations · 2 Risk · 3 Executive summary",
     "outputs": "Commitments at risk = 3 · Cash-flow impact = ₹2.1 Cr · Capacity constraint = Line 3",
     "systems": ["SAP PP", "SAP SD", "WMS", "LIMS/QMS", "CRM", "Finance ERP"],
     "kb": ["Open Sales Orders", "Production Plan", "Inventory", "Forecast & Consumption"],
     "tools": ["SAP_SD_OPEN_ORDERS", "FIN_CASHFLOW", "CRM_CUSTOMER_ORDERS"],
     "rules": [{"name": "Information only — READ mode, no enterprise writeback", "gate": False}],
     "notif": ["In-App Alert"], "workflow": "Information Only"},
]

# ------------------- Simulated enterprise data (SAP/WMS/LIMS) -------------------

SIM_PRODUCTS = {
    "amoxicillin": {"name": "Amoxicillin 500 mg Capsule", "code": "FG-AMOX-500", "line": "Line 3", "rate": 0.5,
                    "materials": [{"m": "API Amoxicillin Trihydrate", "perM": 115, "uom": "kg"},
                                  {"m": "Gelatin capsule shells", "perM": 1.02, "uom": "M units"},
                                  {"m": "Blister foil", "perM": 0.35, "uom": "t"}]},
    "paracetamol": {"name": "Paracetamol 650 mg Tablet", "code": "FG-PARA-650", "line": "Line 1", "rate": 1.2,
                    "materials": [{"m": "API Paracetamol", "perM": 680, "uom": "kg"},
                                  {"m": "Blister foil", "perM": 0.3, "uom": "t"}]},
    "azithromycin": {"name": "Azithromycin 250 mg Tablet", "code": "FG-AZI-250", "line": "Line 2", "rate": 0.4,
                     "materials": [{"m": "API Azithromycin", "perM": 260, "uom": "kg"},
                                   {"m": "Blister foil", "perM": 0.3, "uom": "t"}]},
}

SIM_INVENTORY = {
    "API Amoxicillin Trihydrate": {"stock": 980, "reserved": 160, "uom": "kg", "open_po": 400, "po_eta": "2026-08-05"},
    "Gelatin capsule shells": {"stock": 7.4, "reserved": 1.2, "uom": "M units", "open_po": 6, "po_eta": "2026-06-28"},
    "Blister foil": {"stock": 9.5, "reserved": 0.8, "uom": "t", "open_po": 0, "po_eta": None},
    "API Paracetamol": {"stock": 9500, "reserved": 1200, "uom": "kg", "open_po": 0, "po_eta": None},
    "API Azithromycin": {"stock": 310, "reserved": 40, "uom": "kg", "open_po": 200, "po_eta": "2026-08-20"},
}

SIM_LINES = {"Line 1": "2026-06-15", "Line 2": "2026-08-05", "Line 3": "2026-09-01"}
SIM_QC_RELEASE_DAYS = 7

MATERIAL_ALIASES = {
    "api amoxicillin": "API Amoxicillin Trihydrate", "amoxicillin api": "API Amoxicillin Trihydrate",
    "trihydrate": "API Amoxicillin Trihydrate", "capsule shell": "Gelatin capsule shells",
    "gelatin": "Gelatin capsule shells", "blister": "Blister foil",
    "api paracetamol": "API Paracetamol", "paracetamol api": "API Paracetamol",
    "api azithromycin": "API Azithromycin", "azithromycin api": "API Azithromycin",
}

SEED_USERS = [
    {"username": "admin", "full_name": "Platform Admin", "role": "Admin", "password": "admin123"},
    {"username": "ppic.user", "full_name": "Asha Rao", "role": "PPIC User", "password": "ppic123"},
    {"username": "ppic.head", "full_name": "Vikram Shah", "role": "PPIC Head", "password": "ppic123"},
    {"username": "qa.head", "full_name": "Dr. Meera Iyer", "role": "QA Head", "password": "qa123"},
    {"username": "md", "full_name": "Rajiv Menon", "role": "MD", "password": "md123"},
    {"username": "procurement.head", "full_name": "Sunita Verma", "role": "Procurement Head", "password": "proc123"},
    {"username": "plant.head", "full_name": "Arjun Nair", "role": "Plant Head", "password": "plant123"},
    {"username": "warehouse.head", "full_name": "Kiran Patel", "role": "Warehouse Head", "password": "wh123"},
]
